
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.mycompany.userafncreator;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SintacHoc3 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return SintacHoc3Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public SintacHoc3() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SintacHoc3(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintacHoc3(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\020\000\002\002\004\000\002\002\004\000\002\002" +
    "\002\000\002\003\004\000\002\003\006\000\002\003\004" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\005\000\002\004\006\000\002\004\005\000\002" +
    "\004\005\000\002\004\005\000\002\004\005\000\002\004" +
    "\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\040\000\020\002\uffff\003\uffff\011\uffff\014\uffff\015" +
    "\uffff\016\uffff\017\uffff\001\002\000\020\002\010\003\012" +
    "\011\015\014\005\015\011\016\014\017\006\001\002\000" +
    "\016\005\ufffb\006\ufffb\007\ufffb\010\ufffb\012\ufffb\013\ufffb" +
    "\001\002\000\016\005\ufff9\006\ufff9\007\ufff9\010\ufff9\012" +
    "\ufff9\013\ufff9\001\002\000\020\002\000\003\000\011\000" +
    "\014\000\015\000\016\000\017\000\001\002\000\004\002" +
    "\001\001\002\000\016\004\040\005\ufffa\006\ufffa\007\ufffa" +
    "\010\ufffa\013\ufffa\001\002\000\004\013\037\001\002\000" +
    "\014\005\022\006\020\007\023\010\024\013\036\001\002" +
    "\000\004\011\033\001\002\000\014\011\015\014\005\015" +
    "\016\016\014\017\006\001\002\000\020\004\031\005\ufffa" +
    "\006\ufffa\007\ufffa\010\ufffa\012\ufffa\013\ufffa\001\002\000" +
    "\014\005\022\006\020\007\023\010\024\012\021\001\002" +
    "\000\014\011\015\014\005\015\016\016\014\017\006\001" +
    "\002\000\016\005\ufff2\006\ufff2\007\ufff2\010\ufff2\012\ufff2" +
    "\013\ufff2\001\002\000\014\011\015\014\005\015\016\016" +
    "\014\017\006\001\002\000\014\011\015\014\005\015\016" +
    "\016\014\017\006\001\002\000\014\011\015\014\005\015" +
    "\016\016\014\017\006\001\002\000\016\005\ufff3\006\ufff3" +
    "\007\ufff3\010\ufff3\012\ufff3\013\ufff3\001\002\000\016\005" +
    "\ufff4\006\ufff4\007\ufff4\010\ufff4\012\ufff4\013\ufff4\001\002" +
    "\000\016\005\ufff6\006\ufff6\007\023\010\024\012\ufff6\013" +
    "\ufff6\001\002\000\016\005\ufff5\006\ufff5\007\023\010\024" +
    "\012\ufff5\013\ufff5\001\002\000\014\011\015\014\005\015" +
    "\016\016\014\017\006\001\002\000\016\005\022\006\020" +
    "\007\023\010\024\012\ufff8\013\ufff8\001\002\000\014\011" +
    "\015\014\005\015\016\016\014\017\006\001\002\000\014" +
    "\005\022\006\020\007\023\010\024\012\035\001\002\000" +
    "\016\005\ufff7\006\ufff7\007\ufff7\010\ufff7\012\ufff7\013\ufff7" +
    "\001\002\000\020\002\ufffe\003\ufffe\011\ufffe\014\ufffe\015" +
    "\ufffe\016\ufffe\017\ufffe\001\002\000\020\002\ufffc\003\ufffc" +
    "\011\ufffc\014\ufffc\015\ufffc\016\ufffc\017\ufffc\001\002\000" +
    "\014\011\015\014\005\015\016\016\014\017\006\001\002" +
    "\000\014\005\022\006\020\007\023\010\024\013\ufff8\001" +
    "\002\000\020\002\ufffd\003\ufffd\011\ufffd\014\ufffd\015\ufffd" +
    "\016\ufffd\017\ufffd\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\040\000\004\002\003\001\001\000\006\003\006\004" +
    "\012\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\004\016" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\004" +
    "\027\001\001\000\002\001\001\000\004\004\026\001\001" +
    "\000\004\004\025\001\001\000\004\004\024\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\004\031\001\001\000\002\001\001\000" +
    "\004\004\033\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\004\040\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintacHoc3$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintacHoc3$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintacHoc3$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public MaquinaHoc4 maq;
    public int inicioStmt = 0;

    public SintacHoc3(java_cup.runtime.Scanner s, MaquinaHoc4 maq) {
        super(s);
        this.maq = maq;
    }

    public void report_error(String message, Object info) {
        if (maq.AreaResult != null) {
            maq.AreaResult.append("Error Sintáctico: " + message + "\n");
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SintacHoc3$actions {
  private final SintacHoc3 parser;

  /** Constructor */
  CUP$SintacHoc3$actions(SintacHoc3 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SintacHoc3$do_action_part00000000(
    int                        CUP$SintacHoc3$act_num,
    java_cup.runtime.lr_parser CUP$SintacHoc3$parser,
    java.util.Stack            CUP$SintacHoc3$stack,
    int                        CUP$SintacHoc3$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintacHoc3$result;

      /* select the action based on the action number */
      switch (CUP$SintacHoc3$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= list EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-1)).value;
		RESULT = start_val;
              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintacHoc3$parser.done_parsing();
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // list ::= list stmt 
            {
              Object RESULT =null;

              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("list",0, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // list ::= 
            {
              Object RESULT =null;

              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("list",0, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // stmt ::= expr SEMIC 
            {
              Object RESULT =null;
		 
          maq.code(EnumInstrMaq.PRINT); 
          maq.code(EnumInstrMaq.STOP); 
          maq.execute(inicioStmt); // HOC 3 ejecuta línea por línea
          inicioStmt = maq.progp;
      
              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // stmt ::= VAR ASSIGN expr SEMIC 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-3)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-3)).right;
		SymbolHoc v = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-3)).value;
		 
          maq.code(EnumInstrMaq.ASSIGN); 
          maq.code(EnumInstrMaq.STOP); 
          maq.execute(inicioStmt);
          inicioStmt = maq.progp;
      
              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-3)), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // stmt ::= error SEMIC 
            {
              Object RESULT =null;
		 
          maq.initcode(); // Limpia la memoria en caso de error para no trabarse
          inicioStmt = maq.progp;
      
              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expr ::= NUM 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()).right;
		Float n = (Float)((java_cup.runtime.Symbol) CUP$SintacHoc3$stack.peek()).value;
		 
          SymbolHoc s = maq.TabSimb.install("", EnumTipoSymbol.CONST_PREDEF, n);
          maq.code(EnumInstrMaq.CONSTPUSH);
          maq.code(s);
      
              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expr ::= VAR 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()).right;
		SymbolHoc v = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc3$stack.peek()).value;
		 
          maq.code(EnumInstrMaq.VARPUSH);
          maq.code(v);
          maq.code(EnumInstrMaq.EVAL);
      
              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expr ::= CONST_PREDEF 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()).right;
		SymbolHoc c = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc3$stack.peek()).value;
		
          maq.code(EnumInstrMaq.CONSTPUSH);
          maq.code(c);
      
              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expr ::= VAR ASSIGN expr 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-2)).right;
		SymbolHoc v = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-2)).value;
		
          maq.code(EnumInstrMaq.VARPUSH);
          maq.code(v);
          maq.code(EnumInstrMaq.ASSIGN);
      
              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // expr ::= BLTIN LPAREN expr RPAREN 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-3)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-3)).right;
		SymbolHoc f = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-3)).value;
		
          maq.code(EnumInstrMaq.BLTIN);
          maq.code(f.FuncPredef); /* Toma la función del enum */
      
              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-3)), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // expr ::= expr ADD expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.ADD); 
              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // expr ::= expr SUB expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.SUB); 
              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // expr ::= expr MUL expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.MUL); 
              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // expr ::= expr DIV expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.DIV); 
              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expr ::= LPAREN expr RPAREN 
            {
              Object RESULT =null;

              CUP$SintacHoc3$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.elementAt(CUP$SintacHoc3$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc3$stack.peek()), RESULT);
            }
          return CUP$SintacHoc3$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SintacHoc3$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SintacHoc3$do_action(
    int                        CUP$SintacHoc3$act_num,
    java_cup.runtime.lr_parser CUP$SintacHoc3$parser,
    java.util.Stack            CUP$SintacHoc3$stack,
    int                        CUP$SintacHoc3$top)
    throws java.lang.Exception
    {
              return CUP$SintacHoc3$do_action_part00000000(
                               CUP$SintacHoc3$act_num,
                               CUP$SintacHoc3$parser,
                               CUP$SintacHoc3$stack,
                               CUP$SintacHoc3$top);
    }
}

}
