
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.mycompany.userafncreator;

import java_cup.runtime.*;
import java.util.Stack;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SintacHoc6 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return SintacHoc6Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public SintacHoc6() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SintacHoc6(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintacHoc6(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\073\000\002\002\004\000\002\002\004\000\002\002" +
    "\004\000\002\002\002\000\002\022\002\000\002\005\010" +
    "\000\002\023\002\000\002\005\010\000\002\003\004\000" +
    "\002\003\005\000\002\003\005\000\002\003\004\000\002" +
    "\003\004\000\002\003\005\000\002\003\007\000\002\003" +
    "\004\000\002\003\006\000\002\003\004\000\002\003\005" +
    "\000\002\015\006\000\002\016\005\000\002\017\005\000" +
    "\002\012\004\000\002\014\007\000\002\011\010\000\002" +
    "\010\003\000\002\006\004\000\002\006\002\000\002\013" +
    "\005\000\002\007\004\000\002\007\005\000\002\004\004" +
    "\000\002\004\002\000\002\021\003\000\002\021\003\000" +
    "\002\021\003\000\002\021\006\000\002\021\003\000\002" +
    "\021\005\000\002\021\005\000\002\021\006\000\002\021" +
    "\005\000\002\021\005\000\002\021\005\000\002\021\005" +
    "\000\002\021\004\000\002\021\005\000\002\021\005\000" +
    "\002\021\005\000\002\021\005\000\002\021\005\000\002" +
    "\021\005\000\002\021\005\000\002\021\005\000\002\021" +
    "\004\000\002\021\005\000\002\020\003\000\002\020\004" +
    "\000\002\020\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\175\000\050\002\ufffe\006\ufffe\011\ufffe\013\ufffe\027" +
    "\ufffe\031\ufffe\033\ufffe\034\ufffe\035\ufffe\040\ufffe\041\ufffe" +
    "\042\ufffe\043\ufffe\044\ufffe\045\ufffe\046\ufffe\047\ufffe\050" +
    "\ufffe\051\ufffe\001\002\000\050\002\025\006\021\011\020" +
    "\013\017\027\011\031\015\033\010\034\035\035\013\040" +
    "\032\041\027\042\033\043\026\044\012\045\016\046\023" +
    "\047\040\050\031\051\022\001\002\000\022\006\021\011" +
    "\020\027\011\045\016\046\023\047\040\050\031\051\022" +
    "\001\002\000\034\005\047\006\051\007\054\010\052\015" +
    "\174\017\046\020\055\021\053\022\056\023\045\024\050" +
    "\025\044\026\057\001\002\000\050\002\000\006\000\011" +
    "\000\013\000\027\000\031\000\033\000\034\000\035\000" +
    "\040\000\041\000\042\000\043\000\044\000\045\000\046" +
    "\000\047\000\050\000\051\000\001\002\000\004\011\173" +
    "\001\002\000\022\006\021\011\020\027\011\045\016\046" +
    "\023\047\040\050\031\051\022\001\002\000\024\006\021" +
    "\011\020\015\167\027\011\045\016\046\023\047\040\050" +
    "\031\051\022\001\002\000\004\011\163\001\002\000\022" +
    "\006\021\011\020\027\011\045\016\046\023\047\040\050" +
    "\031\051\022\001\002\000\004\011\154\001\002\000\060" +
    "\004\152\005\uffdc\006\uffdc\007\uffdc\010\uffdc\011\uffdc\012" +
    "\uffdc\015\uffdc\016\uffdc\017\uffdc\020\uffdc\021\uffdc\022\uffdc" +
    "\023\uffdc\024\uffdc\025\uffdc\026\uffdc\027\uffdc\045\uffdc\046" +
    "\uffdc\047\uffdc\050\uffdc\051\uffdc\001\002\000\044\006\uffe1" +
    "\011\uffe1\013\uffe1\014\uffe1\027\uffe1\031\uffe1\033\uffe1\034" +
    "\uffe1\035\uffe1\040\uffe1\041\uffe1\044\uffe1\045\uffe1\046\uffe1" +
    "\047\uffe1\050\uffe1\051\uffe1\001\002\000\022\006\021\011" +
    "\020\027\011\045\016\046\023\047\040\050\031\051\022" +
    "\001\002\000\022\006\021\011\020\027\011\045\016\046" +
    "\023\047\040\050\031\051\022\001\002\000\056\005\uffde" +
    "\006\uffde\007\uffde\010\uffde\011\uffde\012\uffde\015\uffde\016" +
    "\uffde\017\uffde\020\uffde\021\uffde\022\uffde\023\uffde\024\uffde" +
    "\025\uffde\026\uffde\027\uffde\045\uffde\046\uffde\047\uffde\050" +
    "\uffde\051\uffde\001\002\000\056\005\uffe0\006\uffe0\007\uffe0" +
    "\010\uffe0\011\uffe0\012\uffe0\015\uffe0\016\uffe0\017\uffe0\020" +
    "\uffe0\021\uffe0\022\uffe0\023\uffe0\024\uffe0\025\uffe0\026\uffe0" +
    "\027\uffe0\045\uffe0\046\uffe0\047\uffe0\050\uffe0\051\uffe0\001" +
    "\002\000\042\006\021\011\020\013\017\027\011\031\015" +
    "\033\010\034\035\035\013\040\032\041\027\044\012\045" +
    "\016\046\023\047\040\050\031\051\022\001\002\000\004" +
    "\002\001\001\002\000\004\047\137\001\002\000\004\015" +
    "\136\001\002\000\022\006\021\011\020\027\011\045\016" +
    "\046\023\047\040\050\031\051\022\001\002\000\004\011" +
    "\130\001\002\000\022\006\021\011\020\027\011\045\016" +
    "\046\023\047\040\050\031\051\022\001\002\000\004\047" +
    "\121\001\002\000\010\014\uffe6\036\110\037\104\001\002" +
    "\000\004\011\101\001\002\000\050\002\uffff\006\uffff\011" +
    "\uffff\013\uffff\027\uffff\031\uffff\033\uffff\034\uffff\035\uffff" +
    "\040\uffff\041\uffff\042\uffff\043\uffff\044\uffff\045\uffff\046" +
    "\uffff\047\uffff\050\uffff\051\uffff\001\002\000\042\006\021" +
    "\011\020\013\017\027\011\031\015\033\010\034\035\035" +
    "\013\040\032\041\027\044\012\045\016\046\023\047\040" +
    "\050\031\051\022\001\002\000\060\004\042\005\uffdf\006" +
    "\uffdf\007\uffdf\010\uffdf\011\041\012\uffdf\015\uffdf\016\uffdf" +
    "\017\uffdf\020\uffdf\021\uffdf\022\uffdf\023\uffdf\024\uffdf\025" +
    "\uffdf\026\uffdf\027\uffdf\045\uffdf\046\uffdf\047\uffdf\050\uffdf" +
    "\051\uffdf\001\002\000\024\006\021\011\020\012\uffc7\027" +
    "\011\045\016\046\023\047\040\050\031\051\022\001\002" +
    "\000\022\006\021\011\020\027\011\045\016\046\023\047" +
    "\040\050\031\051\022\001\002\000\056\005\047\006\051" +
    "\007\054\010\052\011\uffdb\012\uffdb\015\uffdb\016\uffdb\017" +
    "\046\020\055\021\053\022\056\023\045\024\050\025\044" +
    "\026\057\027\uffdb\045\uffdb\046\uffdb\047\uffdb\050\uffdb\051" +
    "\uffdb\001\002\000\022\006\021\011\020\027\011\045\016" +
    "\046\023\047\040\050\031\051\022\001\002\000\022\006" +
    "\021\011\020\027\011\045\016\046\023\047\040\050\031" +
    "\051\022\001\002\000\022\006\021\011\020\027\011\045" +
    "\016\046\023\047\040\050\031\051\022\001\002\000\022" +
    "\006\021\011\020\027\011\045\016\046\023\047\040\050" +
    "\031\051\022\001\002\000\022\006\021\011\020\027\011" +
    "\045\016\046\023\047\040\050\031\051\022\001\002\000" +
    "\022\006\021\011\020\027\011\045\016\046\023\047\040" +
    "\050\031\051\022\001\002\000\022\006\021\011\020\027" +
    "\011\045\016\046\023\047\040\050\031\051\022\001\002" +
    "\000\022\006\021\011\020\027\011\045\016\046\023\047" +
    "\040\050\031\051\022\001\002\000\022\006\021\011\020" +
    "\027\011\045\016\046\023\047\040\050\031\051\022\001" +
    "\002\000\022\006\021\011\020\027\011\045\016\046\023" +
    "\047\040\050\031\051\022\001\002\000\022\006\021\011" +
    "\020\027\011\045\016\046\023\047\040\050\031\051\022" +
    "\001\002\000\022\006\021\011\020\027\011\045\016\046" +
    "\023\047\040\050\031\051\022\001\002\000\056\005\047" +
    "\006\051\007\054\010\052\011\uffcc\012\uffcc\015\uffcc\016" +
    "\uffcc\017\046\020\055\021\053\022\056\023\045\024\050" +
    "\025\044\026\uffcc\027\uffcc\045\uffcc\046\uffcc\047\uffcc\050" +
    "\uffcc\051\uffcc\001\002\000\056\005\047\006\051\007\054" +
    "\010\052\011\uffd0\012\uffd0\015\uffd0\016\uffd0\017\uffd0\020" +
    "\uffd0\021\uffd0\022\uffd0\023\uffd0\024\uffd0\025\uffd0\026\uffd0" +
    "\027\uffd0\045\uffd0\046\uffd0\047\uffd0\050\uffd0\051\uffd0\001" +
    "\002\000\056\005\047\006\051\007\054\010\052\011\uffd2" +
    "\012\uffd2\015\uffd2\016\uffd2\017\uffd2\020\uffd2\021\053\022" +
    "\056\023\045\024\050\025\uffd2\026\uffd2\027\uffd2\045\uffd2" +
    "\046\uffd2\047\uffd2\050\uffd2\051\uffd2\001\002\000\056\005" +
    "\uffd6\006\uffd6\007\uffd6\010\uffd6\011\uffd6\012\uffd6\015\uffd6" +
    "\016\uffd6\017\uffd6\020\uffd6\021\uffd6\022\uffd6\023\uffd6\024" +
    "\uffd6\025\uffd6\026\uffd6\027\uffd6\045\uffd6\046\uffd6\047\uffd6" +
    "\050\uffd6\051\uffd6\001\002\000\056\005\047\006\051\007" +
    "\054\010\052\011\uffd1\012\uffd1\015\uffd1\016\uffd1\017\uffd1" +
    "\020\uffd1\021\uffd1\022\uffd1\023\uffd1\024\uffd1\025\uffd1\026" +
    "\uffd1\027\uffd1\045\uffd1\046\uffd1\047\uffd1\050\uffd1\051\uffd1" +
    "\001\002\000\056\005\uffd5\006\uffd5\007\uffd5\010\uffd5\011" +
    "\uffd5\012\uffd5\015\uffd5\016\uffd5\017\uffd5\020\uffd5\021\uffd5" +
    "\022\uffd5\023\uffd5\024\uffd5\025\uffd5\026\uffd5\027\uffd5\045" +
    "\uffd5\046\uffd5\047\uffd5\050\uffd5\051\uffd5\001\002\000\056" +
    "\005\uffd7\006\uffd7\007\054\010\052\011\uffd7\012\uffd7\015" +
    "\uffd7\016\uffd7\017\uffd7\020\uffd7\021\uffd7\022\uffd7\023\uffd7" +
    "\024\uffd7\025\uffd7\026\uffd7\027\uffd7\045\uffd7\046\uffd7\047" +
    "\uffd7\050\uffd7\051\uffd7\001\002\000\056\005\047\006\051" +
    "\007\054\010\052\011\uffce\012\uffce\015\uffce\016\uffce\017" +
    "\uffce\020\uffce\021\uffce\022\uffce\023\uffce\024\uffce\025\uffce" +
    "\026\uffce\027\uffce\045\uffce\046\uffce\047\uffce\050\uffce\051" +
    "\uffce\001\002\000\056\005\uffd8\006\uffd8\007\054\010\052" +
    "\011\uffd8\012\uffd8\015\uffd8\016\uffd8\017\uffd8\020\uffd8\021" +
    "\uffd8\022\uffd8\023\uffd8\024\uffd8\025\uffd8\026\uffd8\027\uffd8" +
    "\045\uffd8\046\uffd8\047\uffd8\050\uffd8\051\uffd8\001\002\000" +
    "\056\005\047\006\051\007\054\010\052\011\uffd3\012\uffd3" +
    "\015\uffd3\016\uffd3\017\uffd3\020\uffd3\021\053\022\056\023" +
    "\045\024\050\025\uffd3\026\uffd3\027\uffd3\045\uffd3\046\uffd3" +
    "\047\uffd3\050\uffd3\051\uffd3\001\002\000\056\005\047\006" +
    "\051\007\054\010\052\011\uffcf\012\uffcf\015\uffcf\016\uffcf" +
    "\017\uffcf\020\uffcf\021\uffcf\022\uffcf\023\uffcf\024\uffcf\025" +
    "\uffcf\026\uffcf\027\uffcf\045\uffcf\046\uffcf\047\uffcf\050\uffcf" +
    "\051\uffcf\001\002\000\056\005\047\006\051\007\054\010" +
    "\052\011\uffcd\012\uffcd\015\uffcd\016\uffcd\017\046\020\055" +
    "\021\053\022\056\023\045\024\050\025\uffcd\026\uffcd\027" +
    "\uffcd\045\uffcd\046\uffcd\047\uffcd\050\uffcd\051\uffcd\001\002" +
    "\000\024\006\021\011\020\012\076\027\011\045\016\046" +
    "\023\047\040\050\031\051\022\001\002\000\052\005\047" +
    "\006\051\007\054\010\052\011\uffc9\012\uffc9\017\046\020" +
    "\055\021\053\022\056\023\045\024\050\025\044\026\057" +
    "\027\uffc9\045\uffc9\046\uffc9\047\uffc9\050\uffc9\051\uffc9\001" +
    "\002\000\056\005\uffd9\006\uffd9\007\uffd9\010\uffd9\011\uffd9" +
    "\012\uffd9\015\uffd9\016\uffd9\017\uffd9\020\uffd9\021\uffd9\022" +
    "\uffd9\023\uffd9\024\uffd9\025\uffd9\026\uffd9\027\uffd9\045\uffd9" +
    "\046\uffd9\047\uffd9\050\uffd9\051\uffd9\001\002\000\052\005" +
    "\047\006\051\007\054\010\052\011\uffc8\012\uffc8\017\046" +
    "\020\055\021\053\022\056\023\045\024\050\025\044\026" +
    "\057\027\uffc8\045\uffc8\046\uffc8\047\uffc8\050\uffc8\051\uffc8" +
    "\001\002\000\060\002\ufff0\006\ufff0\011\ufff0\013\ufff0\014" +
    "\ufff0\027\ufff0\031\ufff0\032\ufff0\033\ufff0\034\ufff0\035\ufff0" +
    "\036\ufff0\037\ufff0\040\ufff0\041\ufff0\042\ufff0\043\ufff0\044" +
    "\ufff0\045\ufff0\046\ufff0\047\ufff0\050\ufff0\051\ufff0\001\002" +
    "\000\022\006\021\011\020\027\011\045\016\046\023\047" +
    "\040\050\031\051\022\001\002\000\034\005\047\006\051" +
    "\007\054\010\052\015\103\017\046\020\055\021\053\022" +
    "\056\023\045\024\050\025\044\026\057\001\002\000\022" +
    "\006\uffee\011\uffee\027\uffee\045\uffee\046\uffee\047\uffee\050" +
    "\uffee\051\uffee\001\002\000\004\016\117\001\002\000\004" +
    "\014\116\001\002\000\010\014\uffe6\036\110\037\104\001" +
    "\002\000\050\006\uffe1\011\uffe1\013\uffe1\014\uffe1\027\uffe1" +
    "\031\uffe1\033\uffe1\034\uffe1\035\uffe1\036\uffe1\037\uffe1\040" +
    "\uffe1\041\uffe1\044\uffe1\045\uffe1\046\uffe1\047\uffe1\050\uffe1" +
    "\051\uffe1\001\002\000\022\006\021\011\020\027\011\045" +
    "\016\046\023\047\040\050\031\051\022\001\002\000\034" +
    "\005\047\006\051\007\054\010\052\016\112\017\046\020" +
    "\055\021\053\022\056\023\045\024\050\025\044\026\057" +
    "\001\002\000\050\006\uffe5\011\uffe5\013\uffe5\014\uffe5\027" +
    "\uffe5\031\uffe5\033\uffe5\034\uffe5\035\uffe5\036\uffe5\037\uffe5" +
    "\040\uffe5\041\uffe5\044\uffe5\045\uffe5\046\uffe5\047\uffe5\050" +
    "\uffe5\051\uffe5\001\002\000\050\006\021\011\020\013\017" +
    "\014\uffe4\027\011\031\015\033\010\034\035\035\013\036" +
    "\uffe4\037\uffe4\040\032\041\027\044\012\045\016\046\023" +
    "\047\040\050\031\051\022\001\002\000\050\006\uffe2\011" +
    "\uffe2\013\uffe2\014\uffe2\027\uffe2\031\uffe2\033\uffe2\034\uffe2" +
    "\035\uffe2\036\uffe2\037\uffe2\040\uffe2\041\uffe2\044\uffe2\045" +
    "\uffe2\046\uffe2\047\uffe2\050\uffe2\051\uffe2\001\002\000\004" +
    "\014\uffe7\001\002\000\060\002\uffef\006\uffef\011\uffef\013" +
    "\uffef\014\uffef\027\uffef\031\uffef\032\uffef\033\uffef\034\uffef" +
    "\035\uffef\036\uffef\037\uffef\040\uffef\041\uffef\042\uffef\043" +
    "\uffef\044\uffef\045\uffef\046\uffef\047\uffef\050\uffef\051\uffef" +
    "\001\002\000\050\006\uffe1\011\uffe1\013\uffe1\014\uffe1\027" +
    "\uffe1\031\uffe1\033\uffe1\034\uffe1\035\uffe1\036\uffe1\037\uffe1" +
    "\040\uffe1\041\uffe1\044\uffe1\045\uffe1\046\uffe1\047\uffe1\050" +
    "\uffe1\051\uffe1\001\002\000\050\006\021\011\020\013\017" +
    "\014\uffe3\027\011\031\015\033\010\034\035\035\013\036" +
    "\uffe3\037\uffe3\040\032\041\027\044\012\045\016\046\023" +
    "\047\040\050\031\051\022\001\002\000\004\011\ufffb\001" +
    "\002\000\004\011\123\001\002\000\004\012\124\001\002" +
    "\000\042\006\021\011\020\013\017\027\011\031\015\033" +
    "\010\034\035\035\013\040\032\041\027\044\012\045\016" +
    "\046\023\047\040\050\031\051\022\001\002\000\050\002" +
    "\ufffa\006\ufffa\011\ufffa\013\ufffa\027\ufffa\031\ufffa\033\ufffa" +
    "\034\ufffa\035\ufffa\040\ufffa\041\ufffa\042\ufffa\043\ufffa\044" +
    "\ufffa\045\ufffa\046\ufffa\047\ufffa\050\ufffa\051\ufffa\001\002" +
    "\000\034\005\047\006\051\007\054\010\052\015\127\017" +
    "\046\020\055\021\053\022\056\023\045\024\050\025\044" +
    "\026\057\001\002\000\060\002\ufff8\006\ufff8\011\ufff8\013" +
    "\ufff8\014\ufff8\027\ufff8\031\ufff8\032\ufff8\033\ufff8\034\ufff8" +
    "\035\ufff8\036\ufff8\037\ufff8\040\ufff8\041\ufff8\042\ufff8\043" +
    "\ufff8\044\ufff8\045\ufff8\046\ufff8\047\ufff8\050\ufff8\051\ufff8" +
    "\001\002\000\022\006\021\011\020\027\011\045\016\046" +
    "\023\047\040\050\031\051\022\001\002\000\034\005\047" +
    "\006\051\007\054\010\052\012\132\017\046\020\055\021" +
    "\053\022\056\023\045\024\050\025\044\026\057\001\002" +
    "\000\056\005\uffdd\006\uffdd\007\uffdd\010\uffdd\011\uffdd\012" +
    "\uffdd\015\uffdd\016\uffdd\017\uffdd\020\uffdd\021\uffdd\022\uffdd" +
    "\023\uffdd\024\uffdd\025\uffdd\026\uffdd\027\uffdd\045\uffdd\046" +
    "\uffdd\047\uffdd\050\uffdd\051\uffdd\001\002\000\004\015\135" +
    "\001\002\000\036\005\047\006\051\007\054\010\052\012" +
    "\uffe8\015\uffe8\017\046\020\055\021\053\022\056\023\045" +
    "\024\050\025\044\026\057\001\002\000\022\006\uffed\011" +
    "\uffed\027\uffed\045\uffed\046\uffed\047\uffed\050\uffed\051\uffed" +
    "\001\002\000\060\002\ufff5\006\ufff5\011\ufff5\013\ufff5\014" +
    "\ufff5\027\ufff5\031\ufff5\032\ufff5\033\ufff5\034\ufff5\035\ufff5" +
    "\036\ufff5\037\ufff5\040\ufff5\041\ufff5\042\ufff5\043\ufff5\044" +
    "\ufff5\045\ufff5\046\ufff5\047\ufff5\050\ufff5\051\ufff5\001\002" +
    "\000\004\011\ufffd\001\002\000\004\011\141\001\002\000" +
    "\004\012\142\001\002\000\042\006\021\011\020\013\017" +
    "\027\011\031\015\033\010\034\035\035\013\040\032\041" +
    "\027\044\012\045\016\046\023\047\040\050\031\051\022" +
    "\001\002\000\050\002\ufffc\006\ufffc\011\ufffc\013\ufffc\027" +
    "\ufffc\031\ufffc\033\ufffc\034\ufffc\035\ufffc\040\ufffc\041\ufffc" +
    "\042\ufffc\043\ufffc\044\ufffc\045\ufffc\046\ufffc\047\ufffc\050" +
    "\ufffc\051\ufffc\001\002\000\060\002\ufff2\006\ufff2\011\ufff2" +
    "\013\ufff2\014\ufff2\027\ufff2\031\ufff2\032\ufff2\033\ufff2\034" +
    "\ufff2\035\ufff2\036\ufff2\037\ufff2\040\ufff2\041\ufff2\042\ufff2" +
    "\043\ufff2\044\ufff2\045\ufff2\046\ufff2\047\ufff2\050\ufff2\051" +
    "\ufff2\001\002\000\056\005\uffd4\006\uffd4\007\uffd4\010\uffd4" +
    "\011\uffd4\012\uffd4\015\uffd4\016\uffd4\017\uffd4\020\uffd4\021" +
    "\uffd4\022\uffd4\023\uffd4\024\uffd4\025\uffd4\026\uffd4\027\uffd4" +
    "\045\uffd4\046\uffd4\047\uffd4\050\uffd4\051\uffd4\001\002\000" +
    "\034\005\047\006\051\007\054\010\052\012\147\017\046" +
    "\020\055\021\053\022\056\023\045\024\050\025\044\026" +
    "\057\001\002\000\056\005\uffca\006\uffca\007\uffca\010\uffca" +
    "\011\uffca\012\uffca\015\uffca\016\uffca\017\uffca\020\uffca\021" +
    "\uffca\022\uffca\023\uffca\024\uffca\025\uffca\026\uffca\027\uffca" +
    "\045\uffca\046\uffca\047\uffca\050\uffca\051\uffca\001\002\000" +
    "\044\006\021\011\020\013\017\014\151\027\011\031\015" +
    "\033\010\034\035\035\013\040\032\041\027\044\012\045" +
    "\016\046\023\047\040\050\031\051\022\001\002\000\060" +
    "\002\ufff4\006\ufff4\011\ufff4\013\ufff4\014\ufff4\027\ufff4\031" +
    "\ufff4\032\ufff4\033\ufff4\034\ufff4\035\ufff4\036\ufff4\037\ufff4" +
    "\040\ufff4\041\ufff4\042\ufff4\043\ufff4\044\ufff4\045\ufff4\046" +
    "\ufff4\047\ufff4\050\ufff4\051\ufff4\001\002\000\022\006\021" +
    "\011\020\027\011\045\016\046\023\047\040\050\031\051" +
    "\022\001\002\000\056\005\047\006\051\007\054\010\052" +
    "\011\uffda\012\uffda\015\uffda\016\uffda\017\046\020\055\021" +
    "\053\022\056\023\045\024\050\025\044\026\057\027\uffda" +
    "\045\uffda\046\uffda\047\uffda\050\uffda\051\uffda\001\002\000" +
    "\022\006\021\011\020\027\011\045\016\046\023\047\040" +
    "\050\031\051\022\001\002\000\004\012\156\001\002\000" +
    "\042\006\021\011\020\013\017\027\011\031\015\033\010" +
    "\034\035\035\013\040\032\041\027\044\012\045\016\046" +
    "\023\047\040\050\031\051\022\001\002\000\060\002\ufff3" +
    "\006\ufff3\011\ufff3\013\ufff3\014\ufff3\027\ufff3\031\ufff3\032" +
    "\160\033\ufff3\034\ufff3\035\ufff3\036\ufff3\037\ufff3\040\ufff3" +
    "\041\ufff3\042\ufff3\043\ufff3\044\ufff3\045\ufff3\046\ufff3\047" +
    "\ufff3\050\ufff3\051\ufff3\001\002\000\042\006\uffe9\011\uffe9" +
    "\013\uffe9\027\uffe9\031\uffe9\033\uffe9\034\uffe9\035\uffe9\040" +
    "\uffe9\041\uffe9\044\uffe9\045\uffe9\046\uffe9\047\uffe9\050\uffe9" +
    "\051\uffe9\001\002\000\034\005\047\006\051\007\054\010" +
    "\052\012\162\017\046\020\055\021\053\022\056\023\045" +
    "\024\050\025\044\026\057\001\002\000\042\006\uffec\011" +
    "\uffec\013\uffec\027\uffec\031\uffec\033\uffec\034\uffec\035\uffec" +
    "\040\uffec\041\uffec\044\uffec\045\uffec\046\uffec\047\uffec\050" +
    "\uffec\051\uffec\001\002\000\022\006\021\011\020\027\011" +
    "\045\016\046\023\047\040\050\031\051\022\001\002\000" +
    "\034\005\047\006\051\007\054\010\052\012\165\017\046" +
    "\020\055\021\053\022\056\023\045\024\050\025\044\026" +
    "\057\001\002\000\004\013\166\001\002\000\010\014\uffea" +
    "\036\uffea\037\uffea\001\002\000\060\002\ufff6\006\ufff6\011" +
    "\ufff6\013\ufff6\014\ufff6\027\ufff6\031\ufff6\032\ufff6\033\ufff6" +
    "\034\ufff6\035\ufff6\036\ufff6\037\ufff6\040\ufff6\041\ufff6\042" +
    "\ufff6\043\ufff6\044\ufff6\045\ufff6\046\ufff6\047\ufff6\050\ufff6" +
    "\051\ufff6\001\002\000\034\005\047\006\051\007\054\010" +
    "\052\015\171\017\046\020\055\021\053\022\056\023\045" +
    "\024\050\025\044\026\057\001\002\000\060\002\ufff7\006" +
    "\ufff7\011\ufff7\013\ufff7\014\ufff7\027\ufff7\031\ufff7\032\ufff7" +
    "\033\ufff7\034\ufff7\035\ufff7\036\ufff7\037\ufff7\040\ufff7\041" +
    "\ufff7\042\ufff7\043\ufff7\044\ufff7\045\ufff7\046\ufff7\047\ufff7" +
    "\050\ufff7\051\ufff7\001\002\000\056\005\uffcb\006\uffcb\007" +
    "\uffcb\010\uffcb\011\uffcb\012\uffcb\015\uffcb\016\uffcb\017\uffcb" +
    "\020\uffcb\021\uffcb\022\uffcb\023\uffcb\024\uffcb\025\uffcb\026" +
    "\uffcb\027\uffcb\045\uffcb\046\uffcb\047\uffcb\050\uffcb\051\uffcb" +
    "\001\002\000\022\006\uffeb\011\uffeb\027\uffeb\045\uffeb\046" +
    "\uffeb\047\uffeb\050\uffeb\051\uffeb\001\002\000\060\002\ufff9" +
    "\006\ufff9\011\ufff9\013\ufff9\014\ufff9\027\ufff9\031\ufff9\032" +
    "\ufff9\033\ufff9\034\ufff9\035\ufff9\036\ufff9\037\ufff9\040\ufff9" +
    "\041\ufff9\042\ufff9\043\ufff9\044\ufff9\045\ufff9\046\ufff9\047" +
    "\ufff9\050\ufff9\051\ufff9\001\002\000\004\012\176\001\002" +
    "\000\042\006\021\011\020\013\017\027\011\031\015\033" +
    "\010\034\035\035\013\040\032\041\027\044\012\045\016" +
    "\046\023\047\040\050\031\051\022\001\002\000\060\002" +
    "\ufff1\006\ufff1\011\ufff1\013\ufff1\014\ufff1\027\ufff1\031\ufff1" +
    "\032\ufff1\033\ufff1\034\ufff1\035\ufff1\036\ufff1\037\ufff1\040" +
    "\ufff1\041\ufff1\042\ufff1\043\ufff1\044\ufff1\045\ufff1\046\ufff1" +
    "\047\ufff1\050\ufff1\051\ufff1\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\175\000\004\002\003\001\001\000\024\003\035\005" +
    "\006\011\023\012\004\014\033\015\027\016\013\017\036" +
    "\021\005\001\001\000\006\010\174\021\133\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\021\171\001\001\000\004\021\167\001\001\000\002\001" +
    "\001\000\004\021\160\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\004\147\001\001\000\004\021\145\001" +
    "\001\000\004\021\144\001\001\000\002\001\001\000\002" +
    "\001\001\000\022\003\143\011\023\012\004\014\033\015" +
    "\027\016\013\017\036\021\005\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\010\132\021" +
    "\133\001\001\000\002\001\001\000\004\021\125\001\001" +
    "\000\002\001\001\000\010\006\104\007\105\013\106\001" +
    "\001\000\002\001\001\000\002\001\001\000\022\003\077" +
    "\011\023\012\004\014\033\015\027\016\013\017\036\021" +
    "\005\001\001\000\002\001\001\000\006\020\073\021\074" +
    "\001\001\000\004\021\042\001\001\000\002\001\001\000" +
    "\004\021\072\001\001\000\004\021\071\001\001\000\004" +
    "\021\070\001\001\000\004\021\067\001\001\000\004\021" +
    "\066\001\001\000\004\021\065\001\001\000\004\021\064" +
    "\001\001\000\004\021\063\001\001\000\004\021\062\001" +
    "\001\000\004\021\061\001\001\000\004\021\060\001\001" +
    "\000\004\021\057\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\021\076\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\021\101\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\006\114\007\105" +
    "\013\106\001\001\000\004\004\112\001\001\000\004\021" +
    "\110\001\001\000\002\001\001\000\002\001\001\000\022" +
    "\003\113\011\023\012\004\014\033\015\027\016\013\017" +
    "\036\021\005\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\004\117\001\001\000\022\003" +
    "\113\011\023\012\004\014\033\015\027\016\013\017\036" +
    "\021\005\001\001\000\004\023\121\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\003\124\011\023\012\004" +
    "\014\033\015\027\016\013\017\036\021\005\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\021\130\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\022\137\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\003\142\011\023\012\004\014\033" +
    "\015\027\016\013\017\036\021\005\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\022\003\113\011\023\012\004\014" +
    "\033\015\027\016\013\017\036\021\005\001\001\000\002" +
    "\001\001\000\004\021\152\001\001\000\002\001\001\000" +
    "\006\010\154\021\133\001\001\000\002\001\001\000\022" +
    "\003\156\011\023\012\004\014\033\015\027\016\013\017" +
    "\036\021\005\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\021\163\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\022\003\176\011\023\012\004\014\033\015" +
    "\027\016\013\017\036\021\005\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintacHoc6$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintacHoc6$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintacHoc6$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public MaquinaHoc4 maq;
    public int inicioStmt = 0;
    // Pila para ir guardando los "hoyos" de memoria de los breaks
    public Stack<ArrayList<Integer>> breakStack = new Stack<>();

    public SintacHoc6(java_cup.runtime.Scanner s, MaquinaHoc4 maq) {
        super(s);
        this.maq = maq;
    }

    public void report_error(String message, Object info) {
        if (maq.AreaResult != null) maq.AreaResult.append("Error Sintáctico: " + message + "\n");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SintacHoc6$actions {
  private final SintacHoc6 parser;

  /** Constructor */
  CUP$SintacHoc6$actions(SintacHoc6 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SintacHoc6$do_action_part00000000(
    int                        CUP$SintacHoc6$act_num,
    java_cup.runtime.lr_parser CUP$SintacHoc6$parser,
    java.util.Stack            CUP$SintacHoc6$stack,
    int                        CUP$SintacHoc6$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintacHoc6$result;

      /* select the action based on the action number */
      switch (CUP$SintacHoc6$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= list EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).value;
		RESULT = start_val;
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintacHoc6$parser.done_parsing();
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // list ::= list defn 
            {
              Object RESULT =null;
		 inicioStmt = maq.progp; 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("list",0, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // list ::= list stmt 
            {
              Object RESULT =null;
		 
          maq.code(EnumInstrMaq.STOP); 
          maq.execute(inicioStmt); 
          inicioStmt = maq.progp; 
      
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("list",0, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // list ::= 
            {
              Object RESULT =null;

              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("list",0, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // NT$0 ::= 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()).right;
		SymbolHoc v = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.peek()).value;
 
          v.TipoSymbol = EnumTipoSymbol.FUNC; 
          v.val = maq.progp; 
      
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("NT$0",16, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // defn ::= FUNC VAR NT$0 LPAREN RPAREN stmt 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-4)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-4)).right;
		SymbolHoc v = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-4)).value;
		 maq.code(EnumInstrMaq.RET); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("defn",3, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-5)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // NT$1 ::= 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()).right;
		SymbolHoc v = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.peek()).value;
 
          v.TipoSymbol = EnumTipoSymbol.PROC; 
          v.val = maq.progp;
      
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("NT$1",17, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // defn ::= PROC VAR NT$1 LPAREN RPAREN stmt 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-4)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-4)).right;
		SymbolHoc v = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-4)).value;
		 maq.code(EnumInstrMaq.PROCRET); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("defn",3, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-5)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // stmt ::= expr SEMIC 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.POP); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // stmt ::= PRINT expr SEMIC 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.PRINT); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmt ::= RETURN expr SEMIC 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.RET); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt ::= RETURN SEMIC 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.PROCRET); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // stmt ::= BREAK SEMIC 
            {
              Object RESULT =null;
		 
          maq.code(EnumInstrMaq.JUMP); 
          int hole = maq.progp; maq.code(0); 
          breakStack.peek().add(hole); 
      
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // stmt ::= LBRACE stmtlist RBRACE 
            {
              Object RESULT =null;

              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // stmt ::= IF LPAREN cond RPAREN stmt 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).value;
		 maq.Prog[c].jump = maq.progp; 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-4)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // stmt ::= if_prefix stmt 
            {
              Object RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).right;
		Integer p = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).value;
		 maq.Prog[p].jump = maq.progp; 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // stmt ::= while_start cond RPAREN stmt 
            {
              Object RESULT =null;
		int wsleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)).left;
		int wsright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)).right;
		Integer ws = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).value;
		 
          maq.code(EnumInstrMaq.JUMP); maq.code(ws);
          maq.Prog[c].jump = maq.progp;
          for(int hole : breakStack.pop()) maq.Prog[hole].jump = maq.progp;
      
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // stmt ::= for_inc stmt 
            {
              Object RESULT =null;
		int fileft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).left;
		int firight = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).right;
		int[] fi = (int[])((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).value;
		
          maq.code(EnumInstrMaq.JUMP); maq.code(fi[2]); 
          maq.Prog[fi[1]].jump = maq.progp; 
          for(int hole : breakStack.pop()) maq.Prog[hole].jump = maq.progp;
      
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // stmt ::= switch_start caselist RBRACE 
            {
              Object RESULT =null;
		
          for(int hole : breakStack.pop()) maq.Prog[hole].jump = maq.progp;
      
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // for_init ::= FOR LPAREN expr SEMIC 
            {
              Integer RESULT =null;
		 maq.code(EnumInstrMaq.POP); RESULT = maq.progp; 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("for_init",11, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // for_cond ::= for_init cond SEMIC 
            {
              int[] RESULT =null;
		int csleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).left;
		int csright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).right;
		Integer cs = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).value;
		 
    maq.code(EnumInstrMaq.JUMP); int j1 = maq.progp; maq.code(0);
    RESULT = new int[]{cs, c, maq.progp, j1}; 

              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("for_cond",12, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // for_inc ::= for_cond expr RPAREN 
            {
              int[] RESULT =null;
		int fcleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).left;
		int fcright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).right;
		int[] fc = (int[])((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).value;
		
    maq.code(EnumInstrMaq.POP);
    maq.code(EnumInstrMaq.JUMP); maq.code(fc[0]); 
    maq.Prog[fc[3]].jump = maq.progp;
    breakStack.push(new ArrayList<Integer>());
    RESULT = fc;

              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("for_inc",13, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // while_start ::= WHILE LPAREN 
            {
              Integer RESULT =null;
		 breakStack.push(new ArrayList<Integer>()); RESULT = maq.progp; 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("while_start",8, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // switch_start ::= SWITCH LPAREN expr RPAREN LBRACE 
            {
              Integer RESULT =null;
		 
    maq.code(EnumInstrMaq.SET_AX); 
    breakStack.push(new ArrayList<Integer>());
    RESULT = 0; 

              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("switch_start",10, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-4)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // if_prefix ::= IF LPAREN cond RPAREN stmt ELSE 
            {
              Integer RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)).value;
		
          maq.code(EnumInstrMaq.JUMP); int j = maq.progp; maq.code(0);
          maq.Prog[c].jump = maq.progp; RESULT = j;
      
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("if_prefix",7, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-5)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // cond ::= expr 
            {
              Integer RESULT =null;
		 maq.code(EnumInstrMaq.JUMP_FALSE); RESULT = maq.progp; maq.code(0); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("cond",6, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // caselist ::= case_stmt caselist 
            {
              Object RESULT =null;

              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("caselist",4, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // caselist ::= 
            {
              Object RESULT =null;

              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("caselist",4, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // case_prefix ::= CASE expr COLON 
            {
              Integer RESULT =null;
		
          maq.code(EnumInstrMaq.PUSH_AX); maq.code(EnumInstrMaq.EQ); maq.code(EnumInstrMaq.JUMP_FALSE);
          RESULT = maq.progp; maq.code(0);

              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("case_prefix",9, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // case_stmt ::= case_prefix stmtlist 
            {
              Object RESULT =null;
		int cpleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).left;
		int cpright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).right;
		Integer cp = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).value;
		 maq.Prog[cp].jump = maq.progp; 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("case_stmt",5, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // case_stmt ::= DEFAULT COLON stmtlist 
            {
              Object RESULT =null;

              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("case_stmt",5, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // stmtlist ::= stmtlist stmt 
            {
              Object RESULT =null;

              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("stmtlist",2, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // stmtlist ::= 
            {
              Object RESULT =null;

              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("stmtlist",2, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expr ::= NUM 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()).right;
		Float n = (Float)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.peek()).value;
		 SymbolHoc s = maq.TabSimb.install("", EnumTipoSymbol.CONST_PREDEF, n); maq.code(EnumInstrMaq.CONSTPUSH); maq.code(s); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr ::= VAR 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()).right;
		SymbolHoc v = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.peek()).value;
		 maq.code(EnumInstrMaq.VARPUSH); maq.code(v); maq.code(EnumInstrMaq.EVAL); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr ::= CONST_PREDEF 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()).right;
		SymbolHoc c = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.peek()).value;
		 maq.code(EnumInstrMaq.CONSTPUSH); maq.code(c); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr ::= BLTIN LPAREN expr RPAREN 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)).right;
		SymbolHoc f = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)).value;
		 maq.code(EnumInstrMaq.BLTIN); maq.code(f.FuncPredef); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr ::= ARG 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()).right;
		Integer a = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.peek()).value;
		 maq.code(EnumInstrMaq.ARGPUSH); maq.code(a); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr ::= VAR ASSIGN expr 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).right;
		SymbolHoc v = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).value;
		 maq.code(EnumInstrMaq.VARPUSH); maq.code(v); maq.code(EnumInstrMaq.ASSIGN); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= ARG ASSIGN expr 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).right;
		Integer a = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)).value;
		 maq.code(EnumInstrMaq.ARGASSIGN); maq.code(a); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= VAR LPAREN arglist RPAREN 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)).right;
		SymbolHoc v = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).value;
		 maq.code(EnumInstrMaq.CALL); maq.code(v); maq.code(n); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-3)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr ::= expr ADD expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.ADD); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr ::= expr SUB expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.SUB); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr ::= expr MUL expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.MUL); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr ::= expr DIV expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.DIV); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= SUB expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.CONSTPUSH); maq.code(new SymbolHoc("", EnumTipoSymbol.CONST_PREDEF, -1.0f)); maq.code(EnumInstrMaq.MUL); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= expr EQ expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.EQ); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr ::= expr NE expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.NE); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr ::= expr GT expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.GT); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= expr LT expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.LT); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= expr GE expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.GE); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= expr LE expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.LE); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr ::= expr AND expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.AND); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr ::= expr OR expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.OR); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expr ::= NOT expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.NOT); 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr ::= LPAREN expr RPAREN 
            {
              Object RESULT =null;

              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("expr",15, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // arglist ::= expr 
            {
              Integer RESULT =null;
		 RESULT = 1; 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("arglist",14, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // arglist ::= arglist expr 
            {
              Integer RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)).value;
		 RESULT = n + 1; 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("arglist",14, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.elementAt(CUP$SintacHoc6$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // arglist ::= 
            {
              Integer RESULT =null;
		 RESULT = 0; 
              CUP$SintacHoc6$result = parser.getSymbolFactory().newSymbol("arglist",14, ((java_cup.runtime.Symbol)CUP$SintacHoc6$stack.peek()), RESULT);
            }
          return CUP$SintacHoc6$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SintacHoc6$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SintacHoc6$do_action(
    int                        CUP$SintacHoc6$act_num,
    java_cup.runtime.lr_parser CUP$SintacHoc6$parser,
    java.util.Stack            CUP$SintacHoc6$stack,
    int                        CUP$SintacHoc6$top)
    throws java.lang.Exception
    {
              return CUP$SintacHoc6$do_action_part00000000(
                               CUP$SintacHoc6$act_num,
                               CUP$SintacHoc6$parser,
                               CUP$SintacHoc6$stack,
                               CUP$SintacHoc6$top);
    }
}

}
