
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.mycompany.userafncreator;

/** CUP generated class containing symbol constants. */
public class SintacHoc6Sym {
  /* terminals */
  public static final int CONST_PREDEF = 39;
  public static final int GE = 17;
  public static final int CASE = 28;
  public static final int SEMIC = 11;
  public static final int LPAREN = 7;
  public static final int FOR = 26;
  public static final int RPAREN = 8;
  public static final int NOT = 21;
  public static final int AND = 19;
  public static final int LT = 16;
  public static final int UNARYMINUS = 22;
  public static final int OR = 20;
  public static final int DIV = 6;
  public static final int NUM = 36;
  public static final int ASSIGN = 2;
  public static final int IF = 23;
  public static final int LE = 18;
  public static final int EOF = 0;
  public static final int RETURN = 34;
  public static final int error = 1;
  public static final int MUL = 5;
  public static final int ADD = 3;
  public static final int BREAK = 31;
  public static final int EQ = 13;
  public static final int SWITCH = 27;
  public static final int COLON = 12;
  public static final int LBRACE = 9;
  public static final int ELSE = 24;
  public static final int FUNC = 33;
  public static final int BLTIN = 38;
  public static final int WHILE = 25;
  public static final int DEFAULT = 29;
  public static final int RBRACE = 10;
  public static final int NE = 14;
  public static final int PROC = 32;
  public static final int GT = 15;
  public static final int SUB = 4;
  public static final int VAR = 37;
  public static final int ARG = 35;
  public static final int PRINT = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "ADD",
  "SUB",
  "MUL",
  "DIV",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "SEMIC",
  "COLON",
  "EQ",
  "NE",
  "GT",
  "LT",
  "GE",
  "LE",
  "AND",
  "OR",
  "NOT",
  "UNARYMINUS",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "PRINT",
  "BREAK",
  "PROC",
  "FUNC",
  "RETURN",
  "ARG",
  "NUM",
  "VAR",
  "BLTIN",
  "CONST_PREDEF"
  };
}

