
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.mycompany.userafncreator;

/** CUP generated class containing symbol constants. */
public class SintacHoc3Sym {
  /* terminals */
  public static final int NUM = 10;
  public static final int CONST_PREDEF = 13;
  public static final int SEMIC = 9;
  public static final int EOF = 0;
  public static final int VAR = 11;
  public static final int ADD = 3;
  public static final int SUB = 4;
  public static final int DIV = 6;
  public static final int ASSIGN = 2;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int MUL = 5;
  public static final int BLTIN = 12;
  public static final int LPAREN = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "ADD",
  "SUB",
  "MUL",
  "DIV",
  "LPAREN",
  "RPAREN",
  "SEMIC",
  "NUM",
  "VAR",
  "BLTIN",
  "CONST_PREDEF"
  };
}

