
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.mycompany.userafncreator;

import java_cup.runtime.*;
import java.util.Stack;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SintacHoc5 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return SintacHoc5Sym.class;
}

  /** Default constructor. */
  @Deprecated
  public SintacHoc5() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SintacHoc5(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintacHoc5(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\056\000\002\002\004\000\002\002\004\000\002\002" +
    "\002\000\002\003\004\000\002\003\005\000\002\003\004" +
    "\000\002\003\005\000\002\003\007\000\002\003\004\000" +
    "\002\003\006\000\002\003\004\000\002\003\005\000\002" +
    "\014\006\000\002\015\005\000\002\016\005\000\002\011" +
    "\004\000\002\013\007\000\002\010\010\000\002\007\003" +
    "\000\002\005\004\000\002\005\002\000\002\012\005\000" +
    "\002\006\004\000\002\006\005\000\002\004\004\000\002" +
    "\004\002\000\002\017\003\000\002\017\003\000\002\017" +
    "\003\000\002\017\006\000\002\017\005\000\002\017\005" +
    "\000\002\017\005\000\002\017\005\000\002\017\005\000" +
    "\002\017\004\000\002\017\005\000\002\017\005\000\002" +
    "\017\005\000\002\017\005\000\002\017\005\000\002\017" +
    "\005\000\002\017\005\000\002\017\005\000\002\017\004" +
    "\000\002\017\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\144\000\040\002\uffff\006\uffff\011\uffff\013\uffff\027" +
    "\uffff\031\uffff\033\uffff\034\uffff\035\uffff\040\uffff\041\uffff" +
    "\042\uffff\043\uffff\044\uffff\045\uffff\001\002\000\040\002" +
    "\022\006\016\011\014\013\015\027\010\031\013\033\007" +
    "\034\030\035\011\040\026\041\024\042\020\043\033\044" +
    "\025\045\017\001\002\000\020\006\016\011\014\027\010" +
    "\042\020\043\033\044\025\045\017\001\002\000\034\005" +
    "\041\006\043\007\047\010\045\015\143\017\040\020\046" +
    "\021\044\022\050\023\037\024\042\025\036\026\051\001" +
    "\002\000\004\011\142\001\002\000\020\006\016\011\014" +
    "\027\010\042\020\043\033\044\025\045\017\001\002\000" +
    "\004\011\135\001\002\000\020\006\016\011\014\027\010" +
    "\042\020\043\033\044\025\045\017\001\002\000\004\011" +
    "\126\001\002\000\020\006\016\011\014\027\010\042\020" +
    "\043\033\044\025\045\017\001\002\000\040\006\uffe8\011" +
    "\uffe8\013\uffe8\014\uffe8\027\uffe8\031\uffe8\033\uffe8\034\uffe8" +
    "\035\uffe8\040\uffe8\041\uffe8\042\uffe8\043\uffe8\044\uffe8\045" +
    "\uffe8\001\002\000\020\006\016\011\014\027\010\042\020" +
    "\043\033\044\025\045\017\001\002\000\040\005\uffe5\006" +
    "\uffe5\007\uffe5\010\uffe5\012\uffe5\015\uffe5\016\uffe5\017\uffe5" +
    "\020\uffe5\021\uffe5\022\uffe5\023\uffe5\024\uffe5\025\uffe5\026" +
    "\uffe5\001\002\000\040\005\uffe7\006\uffe7\007\uffe7\010\uffe7" +
    "\012\uffe7\015\uffe7\016\uffe7\017\uffe7\020\uffe7\021\uffe7\022" +
    "\uffe7\023\uffe7\024\uffe7\025\uffe7\026\uffe7\001\002\000\036" +
    "\006\016\011\014\013\015\027\010\031\013\033\007\034" +
    "\030\035\011\040\026\041\024\042\020\043\033\044\025" +
    "\045\017\001\002\000\004\002\001\001\002\000\020\006" +
    "\016\011\014\027\010\042\020\043\033\044\025\045\017" +
    "\001\002\000\004\015\114\001\002\000\004\011\111\001" +
    "\002\000\020\006\016\011\014\027\010\042\020\043\033" +
    "\044\025\045\017\001\002\000\010\014\uffed\036\076\037" +
    "\072\001\002\000\004\011\067\001\002\000\040\002\000" +
    "\006\000\011\000\013\000\027\000\031\000\033\000\034" +
    "\000\035\000\040\000\041\000\042\000\043\000\044\000" +
    "\045\000\001\002\000\036\006\016\011\014\013\015\027" +
    "\010\031\013\033\007\034\030\035\011\040\026\041\024" +
    "\042\020\043\033\044\025\045\017\001\002\000\042\004" +
    "\034\005\uffe6\006\uffe6\007\uffe6\010\uffe6\012\uffe6\015\uffe6" +
    "\016\uffe6\017\uffe6\020\uffe6\021\uffe6\022\uffe6\023\uffe6\024" +
    "\uffe6\025\uffe6\026\uffe6\001\002\000\020\006\016\011\014" +
    "\027\010\042\020\043\033\044\025\045\017\001\002\000" +
    "\040\005\041\006\043\007\047\010\045\012\uffe3\015\uffe3" +
    "\016\uffe3\017\040\020\046\021\044\022\050\023\037\024" +
    "\042\025\036\026\051\001\002\000\020\006\016\011\014" +
    "\027\010\042\020\043\033\044\025\045\017\001\002\000" +
    "\020\006\016\011\014\027\010\042\020\043\033\044\025" +
    "\045\017\001\002\000\020\006\016\011\014\027\010\042" +
    "\020\043\033\044\025\045\017\001\002\000\020\006\016" +
    "\011\014\027\010\042\020\043\033\044\025\045\017\001" +
    "\002\000\020\006\016\011\014\027\010\042\020\043\033" +
    "\044\025\045\017\001\002\000\020\006\016\011\014\027" +
    "\010\042\020\043\033\044\025\045\017\001\002\000\020" +
    "\006\016\011\014\027\010\042\020\043\033\044\025\045" +
    "\017\001\002\000\020\006\016\011\014\027\010\042\020" +
    "\043\033\044\025\045\017\001\002\000\020\006\016\011" +
    "\014\027\010\042\020\043\033\044\025\045\017\001\002" +
    "\000\020\006\016\011\014\027\010\042\020\043\033\044" +
    "\025\045\017\001\002\000\020\006\016\011\014\027\010" +
    "\042\020\043\033\044\025\045\017\001\002\000\020\006" +
    "\016\011\014\027\010\042\020\043\033\044\025\045\017" +
    "\001\002\000\040\005\041\006\043\007\047\010\045\012" +
    "\uffd6\015\uffd6\016\uffd6\017\040\020\046\021\044\022\050" +
    "\023\037\024\042\025\036\026\uffd6\001\002\000\040\005" +
    "\041\006\043\007\047\010\045\012\uffda\015\uffda\016\uffda" +
    "\017\uffda\020\uffda\021\uffda\022\uffda\023\uffda\024\uffda\025" +
    "\uffda\026\uffda\001\002\000\040\005\uffe0\006\uffe0\007\uffe0" +
    "\010\uffe0\012\uffe0\015\uffe0\016\uffe0\017\uffe0\020\uffe0\021" +
    "\uffe0\022\uffe0\023\uffe0\024\uffe0\025\uffe0\026\uffe0\001\002" +
    "\000\040\005\041\006\043\007\047\010\045\012\uffdc\015" +
    "\uffdc\016\uffdc\017\uffdc\020\uffdc\021\044\022\050\023\037" +
    "\024\042\025\uffdc\026\uffdc\001\002\000\040\005\uffdf\006" +
    "\uffdf\007\uffdf\010\uffdf\012\uffdf\015\uffdf\016\uffdf\017\uffdf" +
    "\020\uffdf\021\uffdf\022\uffdf\023\uffdf\024\uffdf\025\uffdf\026" +
    "\uffdf\001\002\000\040\005\041\006\043\007\047\010\045" +
    "\012\uffdb\015\uffdb\016\uffdb\017\uffdb\020\uffdb\021\uffdb\022" +
    "\uffdb\023\uffdb\024\uffdb\025\uffdb\026\uffdb\001\002\000\040" +
    "\005\uffe1\006\uffe1\007\047\010\045\012\uffe1\015\uffe1\016" +
    "\uffe1\017\uffe1\020\uffe1\021\uffe1\022\uffe1\023\uffe1\024\uffe1" +
    "\025\uffe1\026\uffe1\001\002\000\040\005\041\006\043\007" +
    "\047\010\045\012\uffd8\015\uffd8\016\uffd8\017\uffd8\020\uffd8" +
    "\021\uffd8\022\uffd8\023\uffd8\024\uffd8\025\uffd8\026\uffd8\001" +
    "\002\000\040\005\uffe2\006\uffe2\007\047\010\045\012\uffe2" +
    "\015\uffe2\016\uffe2\017\uffe2\020\uffe2\021\uffe2\022\uffe2\023" +
    "\uffe2\024\uffe2\025\uffe2\026\uffe2\001\002\000\040\005\041" +
    "\006\043\007\047\010\045\012\uffdd\015\uffdd\016\uffdd\017" +
    "\uffdd\020\uffdd\021\044\022\050\023\037\024\042\025\uffdd" +
    "\026\uffdd\001\002\000\040\005\041\006\043\007\047\010" +
    "\045\012\uffd9\015\uffd9\016\uffd9\017\uffd9\020\uffd9\021\uffd9" +
    "\022\uffd9\023\uffd9\024\uffd9\025\uffd9\026\uffd9\001\002\000" +
    "\040\005\041\006\043\007\047\010\045\012\uffd7\015\uffd7" +
    "\016\uffd7\017\040\020\046\021\044\022\050\023\037\024" +
    "\042\025\uffd7\026\uffd7\001\002\000\050\002\ufff7\006\ufff7" +
    "\011\ufff7\013\ufff7\014\ufff7\027\ufff7\031\ufff7\032\ufff7\033" +
    "\ufff7\034\ufff7\035\ufff7\036\ufff7\037\ufff7\040\ufff7\041\ufff7" +
    "\042\ufff7\043\ufff7\044\ufff7\045\ufff7\001\002\000\020\006" +
    "\016\011\014\027\010\042\020\043\033\044\025\045\017" +
    "\001\002\000\034\005\041\006\043\007\047\010\045\015" +
    "\071\017\040\020\046\021\044\022\050\023\037\024\042" +
    "\025\036\026\051\001\002\000\020\006\ufff5\011\ufff5\027" +
    "\ufff5\042\ufff5\043\ufff5\044\ufff5\045\ufff5\001\002\000\004" +
    "\016\105\001\002\000\004\014\104\001\002\000\010\014" +
    "\uffed\036\076\037\072\001\002\000\044\006\uffe8\011\uffe8" +
    "\013\uffe8\014\uffe8\027\uffe8\031\uffe8\033\uffe8\034\uffe8\035" +
    "\uffe8\036\uffe8\037\uffe8\040\uffe8\041\uffe8\042\uffe8\043\uffe8" +
    "\044\uffe8\045\uffe8\001\002\000\020\006\016\011\014\027" +
    "\010\042\020\043\033\044\025\045\017\001\002\000\034" +
    "\005\041\006\043\007\047\010\045\016\100\017\040\020" +
    "\046\021\044\022\050\023\037\024\042\025\036\026\051" +
    "\001\002\000\044\006\uffec\011\uffec\013\uffec\014\uffec\027" +
    "\uffec\031\uffec\033\uffec\034\uffec\035\uffec\036\uffec\037\uffec" +
    "\040\uffec\041\uffec\042\uffec\043\uffec\044\uffec\045\uffec\001" +
    "\002\000\044\006\016\011\014\013\015\014\uffeb\027\010" +
    "\031\013\033\007\034\030\035\011\036\uffeb\037\uffeb\040" +
    "\026\041\024\042\020\043\033\044\025\045\017\001\002" +
    "\000\044\006\uffe9\011\uffe9\013\uffe9\014\uffe9\027\uffe9\031" +
    "\uffe9\033\uffe9\034\uffe9\035\uffe9\036\uffe9\037\uffe9\040\uffe9" +
    "\041\uffe9\042\uffe9\043\uffe9\044\uffe9\045\uffe9\001\002\000" +
    "\004\014\uffee\001\002\000\050\002\ufff6\006\ufff6\011\ufff6" +
    "\013\ufff6\014\ufff6\027\ufff6\031\ufff6\032\ufff6\033\ufff6\034" +
    "\ufff6\035\ufff6\036\ufff6\037\ufff6\040\ufff6\041\ufff6\042\ufff6" +
    "\043\ufff6\044\ufff6\045\ufff6\001\002\000\044\006\uffe8\011" +
    "\uffe8\013\uffe8\014\uffe8\027\uffe8\031\uffe8\033\uffe8\034\uffe8" +
    "\035\uffe8\036\uffe8\037\uffe8\040\uffe8\041\uffe8\042\uffe8\043" +
    "\uffe8\044\uffe8\045\uffe8\001\002\000\044\006\016\011\014" +
    "\013\015\014\uffea\027\010\031\013\033\007\034\030\035" +
    "\011\036\uffea\037\uffea\040\026\041\024\042\020\043\033" +
    "\044\025\045\017\001\002\000\034\005\041\006\043\007" +
    "\047\010\045\015\110\017\040\020\046\021\044\022\050" +
    "\023\037\024\042\025\036\026\051\001\002\000\050\002" +
    "\ufffd\006\ufffd\011\ufffd\013\ufffd\014\ufffd\027\ufffd\031\ufffd" +
    "\032\ufffd\033\ufffd\034\ufffd\035\ufffd\036\ufffd\037\ufffd\040" +
    "\ufffd\041\ufffd\042\ufffd\043\ufffd\044\ufffd\045\ufffd\001\002" +
    "\000\020\006\016\011\014\027\010\042\020\043\033\044" +
    "\025\045\017\001\002\000\034\005\041\006\043\007\047" +
    "\010\045\012\113\017\040\020\046\021\044\022\050\023" +
    "\037\024\042\025\036\026\051\001\002\000\040\005\uffe4" +
    "\006\uffe4\007\uffe4\010\uffe4\012\uffe4\015\uffe4\016\uffe4\017" +
    "\uffe4\020\uffe4\021\uffe4\022\uffe4\023\uffe4\024\uffe4\025\uffe4" +
    "\026\uffe4\001\002\000\050\002\ufffc\006\ufffc\011\ufffc\013" +
    "\ufffc\014\ufffc\027\ufffc\031\ufffc\032\ufffc\033\ufffc\034\ufffc" +
    "\035\ufffc\036\ufffc\037\ufffc\040\ufffc\041\ufffc\042\ufffc\043" +
    "\ufffc\044\ufffc\045\ufffc\001\002\000\004\015\117\001\002" +
    "\000\036\005\041\006\043\007\047\010\045\012\uffef\015" +
    "\uffef\017\040\020\046\021\044\022\050\023\037\024\042" +
    "\025\036\026\051\001\002\000\020\006\ufff4\011\ufff4\027" +
    "\ufff4\042\ufff4\043\ufff4\044\ufff4\045\ufff4\001\002\000\050" +
    "\002\ufff9\006\ufff9\011\ufff9\013\ufff9\014\ufff9\027\ufff9\031" +
    "\ufff9\032\ufff9\033\ufff9\034\ufff9\035\ufff9\036\ufff9\037\ufff9" +
    "\040\ufff9\041\ufff9\042\ufff9\043\ufff9\044\ufff9\045\ufff9\001" +
    "\002\000\040\005\uffde\006\uffde\007\uffde\010\uffde\012\uffde" +
    "\015\uffde\016\uffde\017\uffde\020\uffde\021\uffde\022\uffde\023" +
    "\uffde\024\uffde\025\uffde\026\uffde\001\002\000\040\006\016" +
    "\011\014\013\015\014\123\027\010\031\013\033\007\034" +
    "\030\035\011\040\026\041\024\042\020\043\033\044\025" +
    "\045\017\001\002\000\050\002\ufffb\006\ufffb\011\ufffb\013" +
    "\ufffb\014\ufffb\027\ufffb\031\ufffb\032\ufffb\033\ufffb\034\ufffb" +
    "\035\ufffb\036\ufffb\037\ufffb\040\ufffb\041\ufffb\042\ufffb\043" +
    "\ufffb\044\ufffb\045\ufffb\001\002\000\034\005\041\006\043" +
    "\007\047\010\045\012\125\017\040\020\046\021\044\022" +
    "\050\023\037\024\042\025\036\026\051\001\002\000\040" +
    "\005\uffd4\006\uffd4\007\uffd4\010\uffd4\012\uffd4\015\uffd4\016" +
    "\uffd4\017\uffd4\020\uffd4\021\uffd4\022\uffd4\023\uffd4\024\uffd4" +
    "\025\uffd4\026\uffd4\001\002\000\020\006\016\011\014\027" +
    "\010\042\020\043\033\044\025\045\017\001\002\000\004" +
    "\012\130\001\002\000\036\006\016\011\014\013\015\027" +
    "\010\031\013\033\007\034\030\035\011\040\026\041\024" +
    "\042\020\043\033\044\025\045\017\001\002\000\050\002" +
    "\ufffa\006\ufffa\011\ufffa\013\ufffa\014\ufffa\027\ufffa\031\ufffa" +
    "\032\132\033\ufffa\034\ufffa\035\ufffa\036\ufffa\037\ufffa\040" +
    "\ufffa\041\ufffa\042\ufffa\043\ufffa\044\ufffa\045\ufffa\001\002" +
    "\000\036\006\ufff0\011\ufff0\013\ufff0\027\ufff0\031\ufff0\033" +
    "\ufff0\034\ufff0\035\ufff0\040\ufff0\041\ufff0\042\ufff0\043\ufff0" +
    "\044\ufff0\045\ufff0\001\002\000\034\005\041\006\043\007" +
    "\047\010\045\012\134\017\040\020\046\021\044\022\050" +
    "\023\037\024\042\025\036\026\051\001\002\000\036\006" +
    "\ufff3\011\ufff3\013\ufff3\027\ufff3\031\ufff3\033\ufff3\034\ufff3" +
    "\035\ufff3\040\ufff3\041\ufff3\042\ufff3\043\ufff3\044\ufff3\045" +
    "\ufff3\001\002\000\020\006\016\011\014\027\010\042\020" +
    "\043\033\044\025\045\017\001\002\000\034\005\041\006" +
    "\043\007\047\010\045\012\137\017\040\020\046\021\044" +
    "\022\050\023\037\024\042\025\036\026\051\001\002\000" +
    "\004\013\140\001\002\000\010\014\ufff1\036\ufff1\037\ufff1" +
    "\001\002\000\040\005\uffd5\006\uffd5\007\uffd5\010\uffd5\012" +
    "\uffd5\015\uffd5\016\uffd5\017\uffd5\020\uffd5\021\uffd5\022\uffd5" +
    "\023\uffd5\024\uffd5\025\uffd5\026\uffd5\001\002\000\020\006" +
    "\ufff2\011\ufff2\027\ufff2\042\ufff2\043\ufff2\044\ufff2\045\ufff2" +
    "\001\002\000\050\002\ufffe\006\ufffe\011\ufffe\013\ufffe\014" +
    "\ufffe\027\ufffe\031\ufffe\032\ufffe\033\ufffe\034\ufffe\035\ufffe" +
    "\036\ufffe\037\ufffe\040\ufffe\041\ufffe\042\ufffe\043\ufffe\044" +
    "\ufffe\045\ufffe\001\002\000\004\012\145\001\002\000\036" +
    "\006\016\011\014\013\015\027\010\031\013\033\007\034" +
    "\030\035\011\040\026\041\024\042\020\043\033\044\025" +
    "\045\017\001\002\000\050\002\ufff8\006\ufff8\011\ufff8\013" +
    "\ufff8\014\ufff8\027\ufff8\031\ufff8\032\ufff8\033\ufff8\034\ufff8" +
    "\035\ufff8\036\ufff8\037\ufff8\040\ufff8\041\ufff8\042\ufff8\043" +
    "\ufff8\044\ufff8\045\ufff8\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\144\000\004\002\003\001\001\000\022\003\030\010" +
    "\020\011\004\013\026\014\022\015\011\016\031\017\005" +
    "\001\001\000\006\007\143\017\115\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\017\140\001\001\000\002" +
    "\001\001\000\004\017\132\001\001\000\002\001\001\000" +
    "\004\017\123\001\001\000\004\004\121\001\001\000\004" +
    "\017\120\001\001\000\002\001\001\000\002\001\001\000" +
    "\022\003\117\010\020\011\004\013\026\014\022\015\011" +
    "\016\031\017\005\001\001\000\002\001\001\000\006\007" +
    "\114\017\115\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\017\106\001\001\000\010\005\072\006\073\012" +
    "\074\001\001\000\002\001\001\000\002\001\001\000\022" +
    "\003\065\010\020\011\004\013\026\014\022\015\011\016" +
    "\031\017\005\001\001\000\002\001\001\000\004\017\034" +
    "\001\001\000\002\001\001\000\004\017\064\001\001\000" +
    "\004\017\063\001\001\000\004\017\062\001\001\000\004" +
    "\017\061\001\001\000\004\017\060\001\001\000\004\017" +
    "\057\001\001\000\004\017\056\001\001\000\004\017\055" +
    "\001\001\000\004\017\054\001\001\000\004\017\053\001" +
    "\001\000\004\017\052\001\001\000\004\017\051\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\017\067\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\005\102" +
    "\006\073\012\074\001\001\000\004\004\100\001\001\000" +
    "\004\017\076\001\001\000\002\001\001\000\002\001\001" +
    "\000\022\003\101\010\020\011\004\013\026\014\022\015" +
    "\011\016\031\017\005\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\004\105\001\001\000" +
    "\022\003\101\010\020\011\004\013\026\014\022\015\011" +
    "\016\031\017\005\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\017\111\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\022\003\101\010\020\011\004\013\026\014\022\015" +
    "\011\016\031\017\005\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\007\126\017\115\001" +
    "\001\000\002\001\001\000\022\003\130\010\020\011\004" +
    "\013\026\014\022\015\011\016\031\017\005\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\017\135\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\003" +
    "\145\010\020\011\004\013\026\014\022\015\011\016\031" +
    "\017\005\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintacHoc5$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintacHoc5$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintacHoc5$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public MaquinaHoc4 maq;
    public int inicioStmt = 0;
    // Pila para ir guardando los "hoyos" de memoria de los breaks
    public Stack<ArrayList<Integer>> breakStack = new Stack<>();

    public SintacHoc5(java_cup.runtime.Scanner s, MaquinaHoc4 maq) {
        super(s);
        this.maq = maq;
    }

    public void report_error(String message, Object info) {
        if (maq.AreaResult != null) maq.AreaResult.append("Error Sintáctico: " + message + "\n");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SintacHoc5$actions {
  private final SintacHoc5 parser;

  /** Constructor */
  CUP$SintacHoc5$actions(SintacHoc5 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SintacHoc5$do_action_part00000000(
    int                        CUP$SintacHoc5$act_num,
    java_cup.runtime.lr_parser CUP$SintacHoc5$parser,
    java.util.Stack            CUP$SintacHoc5$stack,
    int                        CUP$SintacHoc5$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintacHoc5$result;

      /* select the action based on the action number */
      switch (CUP$SintacHoc5$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= list EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).value;
		RESULT = start_val;
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintacHoc5$parser.done_parsing();
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // list ::= list stmt 
            {
              Object RESULT =null;
		 
          maq.code(EnumInstrMaq.STOP); 
          maq.execute(inicioStmt); 
          inicioStmt = maq.progp; 
      
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("list",0, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // list ::= 
            {
              Object RESULT =null;

              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("list",0, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // stmt ::= expr SEMIC 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.POP); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // stmt ::= PRINT expr SEMIC 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.PRINT); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // stmt ::= BREAK SEMIC 
            {
              Object RESULT =null;
		 
          maq.code(EnumInstrMaq.JUMP); 
          int hole = maq.progp; maq.code(0); 
          breakStack.peek().add(hole); 
      
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // stmt ::= LBRACE stmtlist RBRACE 
            {
              Object RESULT =null;

              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // stmt ::= IF LPAREN cond RPAREN stmt 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).value;
		 maq.Prog[c].jump = maq.progp; 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-4)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // stmt ::= if_prefix stmt 
            {
              Object RESULT =null;
		int pleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).right;
		Integer p = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).value;
		 maq.Prog[p].jump = maq.progp; 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // stmt ::= while_start cond RPAREN stmt 
            {
              Object RESULT =null;
		int wsleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-3)).left;
		int wsright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-3)).right;
		Integer ws = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).value;
		 
          maq.code(EnumInstrMaq.JUMP); maq.code(ws);
          maq.Prog[c].jump = maq.progp;
          for(int hole : breakStack.pop()) maq.Prog[hole].jump = maq.progp;
      
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-3)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmt ::= for_inc stmt 
            {
              Object RESULT =null;
		int fileft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).left;
		int firight = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).right;
		int[] fi = (int[])((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).value;
		
          maq.code(EnumInstrMaq.JUMP); maq.code(fi[2]); 
          maq.Prog[fi[1]].jump = maq.progp; 
          for(int hole : breakStack.pop()) maq.Prog[hole].jump = maq.progp;
      
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt ::= switch_start caselist RBRACE 
            {
              Object RESULT =null;
		
          for(int hole : breakStack.pop()) maq.Prog[hole].jump = maq.progp;
      
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // for_init ::= FOR LPAREN expr SEMIC 
            {
              Integer RESULT =null;
		 maq.code(EnumInstrMaq.POP); RESULT = maq.progp; 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("for_init",10, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-3)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // for_cond ::= for_init cond SEMIC 
            {
              int[] RESULT =null;
		int csleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).left;
		int csright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).right;
		Integer cs = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).value;
		 
    maq.code(EnumInstrMaq.JUMP); int j1 = maq.progp; maq.code(0);
    RESULT = new int[]{cs, c, maq.progp, j1}; 

              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("for_cond",11, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // for_inc ::= for_cond expr RPAREN 
            {
              int[] RESULT =null;
		int fcleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).left;
		int fcright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).right;
		int[] fc = (int[])((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).value;
		
    maq.code(EnumInstrMaq.POP);
    maq.code(EnumInstrMaq.JUMP); maq.code(fc[0]); 
    maq.Prog[fc[3]].jump = maq.progp;
    breakStack.push(new ArrayList<Integer>());
    RESULT = fc;

              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("for_inc",12, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // while_start ::= WHILE LPAREN 
            {
              Integer RESULT =null;
		 breakStack.push(new ArrayList<Integer>()); RESULT = maq.progp; 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("while_start",7, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // switch_start ::= SWITCH LPAREN expr RPAREN LBRACE 
            {
              Integer RESULT =null;
		 
    maq.code(EnumInstrMaq.SET_AX); 
    breakStack.push(new ArrayList<Integer>());
    RESULT = 0; 

              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("switch_start",9, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-4)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // if_prefix ::= IF LPAREN cond RPAREN stmt ELSE 
            {
              Integer RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-3)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-3)).right;
		Integer c = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-3)).value;
		
          maq.code(EnumInstrMaq.JUMP); int j = maq.progp; maq.code(0);
          maq.Prog[c].jump = maq.progp; RESULT = j;
      
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("if_prefix",6, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-5)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // cond ::= expr 
            {
              Integer RESULT =null;
		 maq.code(EnumInstrMaq.JUMP_FALSE); RESULT = maq.progp; maq.code(0); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("cond",5, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // caselist ::= case_stmt caselist 
            {
              Object RESULT =null;

              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("caselist",3, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // caselist ::= 
            {
              Object RESULT =null;

              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("caselist",3, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // case_prefix ::= CASE expr COLON 
            {
              Integer RESULT =null;
		
          maq.code(EnumInstrMaq.PUSH_AX); maq.code(EnumInstrMaq.EQ); maq.code(EnumInstrMaq.JUMP_FALSE);
          RESULT = maq.progp; maq.code(0);

              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("case_prefix",8, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // case_stmt ::= case_prefix stmtlist 
            {
              Object RESULT =null;
		int cpleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).left;
		int cpright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).right;
		Integer cp = (Integer)((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)).value;
		 maq.Prog[cp].jump = maq.progp; 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("case_stmt",4, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // case_stmt ::= DEFAULT COLON stmtlist 
            {
              Object RESULT =null;

              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("case_stmt",4, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // stmtlist ::= stmtlist stmt 
            {
              Object RESULT =null;

              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("stmtlist",2, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // stmtlist ::= 
            {
              Object RESULT =null;

              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("stmtlist",2, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr ::= NUM 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()).right;
		Float n = (Float)((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.peek()).value;
		 SymbolHoc s = maq.TabSimb.install("", EnumTipoSymbol.CONST_PREDEF, n); maq.code(EnumInstrMaq.CONSTPUSH); maq.code(s); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expr ::= VAR 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()).right;
		SymbolHoc v = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.peek()).value;
		 maq.code(EnumInstrMaq.VARPUSH); maq.code(v); maq.code(EnumInstrMaq.EVAL); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr ::= CONST_PREDEF 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()).right;
		SymbolHoc c = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.peek()).value;
		 maq.code(EnumInstrMaq.CONSTPUSH); maq.code(c); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expr ::= BLTIN LPAREN expr RPAREN 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-3)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-3)).right;
		SymbolHoc f = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-3)).value;
		 maq.code(EnumInstrMaq.BLTIN); maq.code(f.FuncPredef); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-3)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expr ::= VAR ASSIGN expr 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).right;
		SymbolHoc v = (SymbolHoc)((java_cup.runtime.Symbol) CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)).value;
		 maq.code(EnumInstrMaq.VARPUSH); maq.code(v); maq.code(EnumInstrMaq.ASSIGN); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expr ::= expr ADD expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.ADD); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expr ::= expr SUB expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.SUB); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expr ::= expr MUL expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.MUL); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr ::= expr DIV expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.DIV); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr ::= SUB expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.CONSTPUSH); maq.code(new SymbolHoc("", EnumTipoSymbol.CONST_PREDEF, -1.0f)); maq.code(EnumInstrMaq.MUL); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr ::= expr EQ expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.EQ); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr ::= expr NE expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.NE); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr ::= expr GT expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.GT); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= expr LT expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.LT); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= expr GE expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.GE); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr ::= expr LE expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.LE); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr ::= expr AND expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.AND); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr ::= expr OR expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.OR); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr ::= NOT expr 
            {
              Object RESULT =null;
		 maq.code(EnumInstrMaq.NOT); 
              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-1)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= LPAREN expr RPAREN 
            {
              Object RESULT =null;

              CUP$SintacHoc5$result = parser.getSymbolFactory().newSymbol("expr",13, ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.elementAt(CUP$SintacHoc5$top-2)), ((java_cup.runtime.Symbol)CUP$SintacHoc5$stack.peek()), RESULT);
            }
          return CUP$SintacHoc5$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SintacHoc5$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SintacHoc5$do_action(
    int                        CUP$SintacHoc5$act_num,
    java_cup.runtime.lr_parser CUP$SintacHoc5$parser,
    java.util.Stack            CUP$SintacHoc5$stack,
    int                        CUP$SintacHoc5$top)
    throws java.lang.Exception
    {
              return CUP$SintacHoc5$do_action_part00000000(
                               CUP$SintacHoc5$act_num,
                               CUP$SintacHoc5$parser,
                               CUP$SintacHoc5$stack,
                               CUP$SintacHoc5$top);
    }
}

}
